spring.application.name=smartParkingAndReservation

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/smartparking?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=100MB
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Image Storage
user.image.directory=c:\\Users\\viswa\\OneDrive\\Documents\\TK181219 - Vinay - Smart Online Parking And Reservation System\\TK163983 - Smart Online Parking And Reservation System\\CODE\\server\\src\\main\\resources\\static\\images